# Generated by Django 4.1.7 on 2023-04-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('mail', models.EmailField(max_length=254, verbose_name='Gmail')),
                ('photo', models.ImageField(upload_to='user_photo/')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('info', models.TextField(max_length=500, verbose_name='Краткая информация')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
