# Generated by Django 4.2 on 2023-04-04 22:47

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Адресс'),
        ),
        migrations.AddField(
            model_name='blog',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[blog.models.email_validations], verbose_name='Эмэйл'),
        ),
        migrations.AddField(
            model_name='blog',
            name='instagram',
            field=models.TextField(blank=True, null=True, verbose_name='Соц-сеть Instagram'),
        ),
        migrations.AddField(
            model_name='blog',
            name='phone',
            field=models.BooleanField(blank=True, null=True, verbose_name='Номер'),
        ),
        migrations.AddField(
            model_name='blog',
            name='telegram',
            field=models.TextField(blank=True, null=True, verbose_name='Соц-сеть Telegram'),
        ),
        migrations.AddField(
            model_name='blog',
            name='vk',
            field=models.TextField(blank=True, null=True, verbose_name='Соц-сеть VK'),
        ),
        migrations.AddField(
            model_name='blog',
            name='work',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Профессия'),
        ),
    ]
